<?php echo $this->getContent() ?>

<div align="center">

	<h1>Bienvenue !</h1>
	<div>
		<p>ScrumDev est un site internet permettant de gérer les projets développés avec la méthode agile Scrum.</p>
		<p>Grâce à ScrumDev, vous pourrez rejoindre facilement des projets en cours de développement qui vous intéressent et créer vos propres projets à l'abri des regards ou accessibles à tout le monde.</p>
		<p>Toute la gestion de votre espace se trouve dans la bannière du site, qui comprend les projets disponibles ou encore les tâches à effectuer pour le sprint en cours.</p>
	</div>
</div>