<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>ScrumDev</title>
        <script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
        <link rel="stylesheet" type="text/css" href="http://netdna.bootstrapcdn.com/twitter-bootstrap/2.2.1/css/bootstrap-combined.min.css"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body>

        <div class="navbar navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <a class="brand" href="#">ScrumDev</a>
                    <div class="nav-collapse">
                        <ul class="nav pull-left">
                            <li>
                                <?php echo $this->tag->linkTo('index', 'Accueil') ?>
                            </li>
                            <?php if ($this->session->has('auth')) { ?>
                                <li>
                                    <?php echo $this->tag->linkTo('project/index', '+Projets') ?>
                                </li>
                                <?php if ($this->session->has('id_proj')) { ?>
                                    <li>
                                        <?php echo $this->tag->linkTo('userstory/index', '+Backlog') ?>
                                    </li>
                                    <li>
                                        <?php echo $this->tag->linkTo('sprint/index', '+Sprints') ?>
                                    </li>
									<?php if ($this->session->has('id_sprint')) { ?>
										<li>
											<?php echo $this->tag->linkTo('sprint/kanban', '+Kanban') ?>
										</li>
									<?php } ?>
                                <?php } ?>
                                <li>
                                    <?php echo $this->tag->linkTo('user/logout', 'Déconnexion') ?>
                                </li>
                            <?php } else { ?>
                                <li>
                                    <?php echo $this->tag->linkTo('user/index', 'Connexion') ?>
                                </li>
                            <?php } ?>
                        </ul>
                    </div>
                </div>
            </div>


        <?php echo $this->getContent() ?>

        <script src="http://netdna.bootstrapcdn.com/twitter-bootstrap/2.2.1/js/bootstrap.min.js"></script>
    </body>
</html>