
<?php echo $this->getContent(); ?>

<?php echo $this->tag->form("userstory/save") ?>

<table width="100%">
    <tr>
        <td align="left"><?php echo $this->tag->linkTo(array("backlog/index", "Back")) ?></td>
        <td align="right"><?php echo $this->tag->submitButton("Save") ?></td>
    </tr>
</table>

<div align="center">
    <h1>Edit US</h1>
</div>

<table align="center">
    <tr>
        <td align="right">
            <label for="title">Title</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("title", "size" => 10)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="content">Content</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("content", "size" => 254)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="cost">Coût</label>
        </td>
        <td align="left">
            <?php echo $this->tag->numericField(array("cost")) ?>
        </td>
    </tr>

    <tr>
        <td><?php echo $this->tag->hiddenField("id") ?></td>
        <td><?php echo $this->tag->submitButton("Save") ?></td>
    </tr>
</table>

</form>
