<?php echo $this->getContent();?>

<?php if ($this->session->has('auth')){?>

<table width="100%">
    <tr>
        <td align="left"><?php echo $this->tag->linkTo(array("project/index", "Retour", "class"=>"btn")); ?></td>
        <td align="right"><?php echo $this->tag->linkTo(array("userstory/new", "Nouvelle User Story", "class"=>"btn")) ?></td>
    </tr>
</table>

<h1>Backlog</h1>

<table class="table" style="width:50% !important">
    <thead>
        <tr>
            <td><?php echo "#"; ?></td>
            <td><?php echo "Contenu"; ?></td>
            <td><?php echo "Coût"; ?></td>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($page as $us) { ?>
		<tr>
			<td><?php echo "US",$us->number ?></td>
			<td><?php echo $us->content ?></td>
			<td><?php echo $us->cost ?></td>
			<td><?php echo $this->tag->linkTo(array("userstory/edit/" . $us->id_us, "Modifier")), " / ",
                            $this->tag->linkTo(array("userstory/delete/" . $us->id_us, "Supprimer")); 
            ?></td>
		</tr>
	<?php } ?>
    </tbody>
</table>

<?php } else { 
    $this->flash->error("Vous devez être connecté pour avoir accès à cette page.");
} ?>