<?php echo $this->getContent();?>

<?php if ($this->session->has('auth')){?>

<table width="100%">
    <tr>
        <td align="left"><?php echo $this->tag->linkTo(array("project/index", "Retour", "class"=>"btn")); ?></td>
        <td align="right"><?php echo $this->tag->linkTo(array("userstory/new", "Nouvelle User Story", "class"=>"btn")) ?></td>
    </tr>
</table>

<table class="table">
    <thead>
        <tr>
            <td><?php echo "#"; ?></td>
            <td><?php echo "Contenu"; ?></td>
            <td><?php echo "Coût"; ?></td>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($page as $us) { ?>
		<tr>
			<td><?php echo $us->id_project ?></td>
			<td><?php echo $us->id_us ?></td>
			<td><?php echo $this->tag->linkTo(array("userstory/edit/" . $us->id_us, "Modifier")); ?></td>
			<td><?php echo $this->tag->linkTo(array("backlog/delete/" . $us->id_us, "Supprimer")); ?></td>
		</tr>
	<?php } ?>
    </tbody>
</table>
<table>
	<thead>
		<tr>
			<th>Id of project</th>
			<th>Id of US</th>
		</tr>
	</thead>
	<tbody>
	<?php foreach ($page as $us) { ?>
		<tr>
			<td><?php echo $us->id_us ?></td>
			<td><?php echo $us->userstory->title ?></td>
			<td><?php echo $this->tag->linkTo(array("userstory/edit/" . $us->id_us, "Modifier")); ?></td>
			<td><?php echo $this->tag->linkTo(array("backlog/delete/" . $us->id_us, "Supprimer")); ?></td>
		</tr>
	<?php } ?>
	</tbody>
	
</table>

<?php } else { 
    $this->flash->error("Vous devez être connecté pour avoir accès à cette page.");
} ?>