<?php echo $this->getContent(); ?>

<?php if ($this->session->has('auth')){?>

<table width="100%">
    <tr>
        <td align="left"><?php echo $this->tag->linkTo(array("userstory/index", "Retour", "class"=>"btn")) ?></td>
    </tr>
</table>

<h1>Nouvelle User Story</h1>

<?php echo $this->tag->form("userstory/create") ?>
    <table>
        <tr>
            <td align="right">
                <label for="number">Numéro</label>
            </td>
            <td align="left">
                <?php echo $this->tag->numericField(array("number")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="content">Contenu</label>
            </td>
            <td align="left">
                <?php echo $this->tag->textField(array("content", "size" => 254)) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="cost">Coût</label>
            </td>
            <td align="left">
                <?php echo $this->tag->numericField(array("cost")) ?>
            </td>
        </tr>

        <tr>
            <td></td>
            <td><?php echo $this->tag->submitButton(array("Valider", "class"=>"btn")) ?></td>
        </tr>
    </table>
</form>

<?php } else { 
    $this->flash->error("Vous devez être connecté pour avoir accès à cette page.");
} ?>