<?php use Phalcon\Tag; ?>

<?php echo $this->getContent(); ?>

<table width="100%">
    <tr>
        <td align="left">
            <?php echo $this->tag->linkTo(array("user/index", "Go Back")); ?>
        </td>
    </tr>
</table>

<div align="right">
    <?php echo $this->tag->linkTo(array("userstory/new", "New US")) ?>
	<table class="browse" align="center">
		<thead>
			<tr>
				<th>Id of project</th>
				<th>Id of US</th>
			</tr>
		</thead>
		<tbody>
		<?php foreach ($page->items as $us) { ?>
			<tr>
				<td><?php echo $us->id_project ?></td>
				<td><?php echo $us->id_us ?></td>
				<td><?php echo $this->tag->linkTo(array("userstory/edit/" . $us->id_us, "Edit")); ?></td>
				<td><?php echo $this->tag->linkTo(array("backlog/delete/" . $us->id_us, "Delete")); ?></td>
			</tr>
		<?php } ?>
		</tbody>
		<tbody>
			<tr>
				<td colspan="2" align="right">
					<table align="center">
						<tr>
							<td><?php echo $this->tag->linkTo("backlog/index", "First") ?></td>
							<td><?php echo $this->tag->linkTo("backlog/index?page=" . $page->before, "Previous") ?></td>
							<td><?php echo $this->tag->linkTo("backlog/index?page=" . $page->next, "Next") ?></td>
							<td><?php echo $this->tag->linkTo("backlog/index?page=" . $page->last, "Last") ?></td>
							<td><?php echo $page->current, "/", $page->total_pages ?></td>
						</tr>
					</table>
				</td>
			</tr>
		</tbody>
	</table>
</div>