<?php echo $this->getContent(); ?>

<?php if ($this->session->has('auth')){?>

<table width="100%">
    <tr>
        <td align="left"><?php echo $this->tag->linkTo(array("sprint", "Retour", "class"=>"btn")) ?></td>
        <td align="right"><?php echo $this->tag->submitButton(array("Valider", "class"=>"btn")) ?></td>
    </tr>
</table>

<h1>Edition du sprint</h1>

<?php echo $this->tag->form("sprint/save") ?>
    <table>
        <tr>
            <td align="right">
                <label for="number">Sprint numéro</label>
            </td>
            <td align="left">
                <?php echo $this->tag->numericField(array("number", "type" => "number")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="begin">Début</label>
            </td>
            <td align="left">
                    <?php echo $this->tag->textField(array("begin", "type" => "date")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="end">Fin</label>
            </td>
            <td align="left">
                    <?php echo $this->tag->textField(array("end", "type" => "date")) ?>
            </td>
        </tr>

        <tr>
            <td><?php echo $this->tag->hiddenField("id_sprint") ?></td>
            <td><?php echo $this->tag->submitButton("Save") ?></td>
        </tr>
    </table>
</form>

<?php } else { 
    $this->flash->error("Vous devez être connecté pour avoir accès à cette page.");
} ?>