<?php echo $this->getContent(); ?>

<table width="100%">
    <tr>
        <td align="left"><?php echo $this->tag->linkTo(array("sprint", "Retour", "class" => "btn")) ?></td>
        <td align="right"><?php echo $this->tag->submitButton(array("Valider", "class"=>"btn")) ?></td>
    </tr>
</table>

<h1>Nouveau sprint</h1>

<?php echo $this->tag->form("sprint/create") ?>
    <table>
        <tr>
            <td align="right">
                <label for="number">Sprint numéro</label>
            </td>
            <td align="left">
                <?php echo $this->tag->numericField(array("number", "type" => "number")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="begin">Début</label>
            </td>
            <td align="left">
                    <?php echo $this->tag->dateField(array("begin", "type" => "date")) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="end">Fin</label>
            </td>
            <td align="left">
                    <?php echo $this->tag->dateField(array("end", "type" => "date")) ?>
            </td>
        </tr>
        <tr>
            <td></td>
            <td><?php echo $this->tag->submitButton("Valider") ?></td>
        </tr>
    </table>
</form>
