
<?php echo $this->tag->form("sprint/create") ?>

<table width="100%">
    <tr>
        <td align="left"><?php echo $this->tag->linkTo(array("sprint", "Go Back")) ?></td>
        <td align="right"><?php echo $this->tag->submitButton("Save") ?></td>
    </tr>
</table>

<?php echo $this->getContent(); ?>

<div align="center">
    <h1>Create sprint</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="number">Number</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("number", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="id_project">Id Of Project</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("id_project", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="begin">Begin</label>
        </td>
        <td align="left">
                <?php echo $this->tag->dateField(array("begin", "type" => "date")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="end">End</label>
        </td>
        <td align="left">
                <?php echo $this->tag->dateField(array("end", "type" => "date")) ?>
        </td>
    </tr>

    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Save") ?></td>
    </tr>
</table>

</form>
