<?php echo $this->getContent(); ?>

<?php if ($this->session->has('auth')){?>

<table width="100%">
    <tr>
        <td align="left">
        	<?php echo $this->tag->linkTo(array("sprint/index", "Retour", "class"=>"btn")); ?>
        </td>
        <td align="right">
        <?php if($sprint->status !== "closed" && $sprint->status !== "archived") {
        	echo $this->tag->linkTo(array("sprint/edit/".$sprint->id_sprint, "Modifier", "class"=>"btn"));
        	} ?></td>
    </tr>
    <tr>
    	<td align="left"></td>
    	<td align="right"><?php echo $this->tag->linkTo(array("task/index", "Tâches", "class"=>"btn")); ?></td>
    </tr>
</table>

<h1><?php echo "Sprint ",$sprint->number ?></h1>

<p align="left" style='margin-left:5%'>
	<b>Etat du sprint :</b> <?php echo $prog ?><br/>
</p>

<div align="left" style='margin-left:5%'>
	Liste des User Stories :
</div>
<?php if ($us->count() == 0) { ?>
	<div align="left" style='margin-left:20px'> Ce sprint ne contient aucune Userstory.</div>
<?php } else {  ?>

<table class="table" style="width:80% !important">
	<tr>
		<th>Intitulé</th>
		<th>Contenu</th>
		<th>Coût</th>
		<th>Etat</th>
	</tr>

<?php 	$i = 0;
		foreach($us as $sprUS){ ?>
	<tr>
		<td><?php echo "US" . $sprUS->number ?></td>
		<td><?php echo $sprUS->content ?></td>
		<td><?php echo $sprUS->cost ?></td>
		<td><?php if($status[$i])
					echo "Fait";
				else
					echo "A faire"; ?></td>
	</tr>
<?php 		$i++;
		} ?>
</table>

<?php } ?>


<p align="left" style='margin-left:50px'> <?php echo $this->tag->linkTo(array("sprint/assign/".$sprint->id_sprint, "Modifier les US associées", "class"=>"btn")); ?></p>

<?php echo $this->tag->hiddenField("id_task") ?>

<?php } else { 
    $this->flash->error("Vous devez être connecté pour avoir accès à cette page.");
} ?>

