<?php echo $this->getContent(); ?>

<?php if ($this->session->has('auth')){?>

<table width="100%">
    <tr>
        <td align="left"><?php echo $this->tag->linkTo(array("sprint/index", "Retour", "class"=>"btn")); ?></td>
        <td align="right"><?php echo $this->tag->linkTo(array("sprint/edit/".$sprint->id_sprint, "Modifier", "class"=>"btn")); ?></td>
    </tr>
</table>

<h1><?php echo "Sprint ",$sprint->number ?></h1>

<p align="left" style='margin-left:50px'>
	<b>Etat du sprint :</b> <?php echo $prog ?><br/>
</p>

<div align="left" style='margin-left:50px'>
	Liste des User Stories :
</div>

<table class="table" style="width:80% !important">
	<tr>
		<th>Intitulé</th>
		<th>Contenu</th>
		<th>Coût</th>
	</tr>

<?php foreach($sprint->sprintUs as $sprUS){ ?>
	<tr>
		<td><?php echo $sprUS->userStory->title ?></td>
		<td><?php echo $sprUS->userStory->content ?></td>
		<td><?php echo $sprUS->userStory->cost ?></td>
	</tr>
<?php } ?>
</table>

<?php } else { 
    $this->flash->error("Vous devez être connecté pour avoir accès à cette page.");
} ?>