-- MySQL Script generated by MySQL Workbench
-- 11/25/14 20:36:01
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema scrumdev
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema scrumdev
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `scrumdev` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `scrumdev` ;

-- -----------------------------------------------------
-- Table `scrumdev`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scrumdev`.`user` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(20) NULL,
  `email` VARCHAR(40) NULL,
  `password` VARCHAR(30) NULL,
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `scrumdev`.`project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scrumdev`.`project` (
  `id_project` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  `content` TEXT NULL,
  `access` INT NULL,
  PRIMARY KEY (`id_project`))
ENGINE = InnoDB
COMMENT = '	';


-- -----------------------------------------------------
-- Table `scrumdev`.`member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scrumdev`.`member` (
  `id_member` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT NULL,
  `id_project` INT NULL,
  `status` INT NULL,
  PRIMARY KEY (`id_member`),
  INDEX `id_user_idx` (`id_user` ASC),
  INDEX `id_project_idx` (`id_project` ASC),
  CONSTRAINT `id_user_member`
    FOREIGN KEY (`id_user`)
    REFERENCES `scrumdev`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_project`
    FOREIGN KEY (`id_project`)
    REFERENCES `scrumdev`.`project` (`id_project`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `scrumdev`.`userstory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scrumdev`.`userstory` (
  `id_us` INT NOT NULL AUTO_INCREMENT,
  `id_project` INT NULL,
  `number` INT NULL,
  `content` TEXT NULL,
  `cost` INT NULL,
  `id_sprint` INT NULL,
  PRIMARY KEY (`id_us`),
  INDEX `id_project_idx` (`id_project` ASC),
  CONSTRAINT `id_project_us`
    FOREIGN KEY (`id_project`)
    REFERENCES `scrumdev`.`project` (`id_project`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `scrumdev`.`sprint`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scrumdev`.`sprint` (
  `id_sprint` INT NOT NULL AUTO_INCREMENT,
  `id_project` INT NULL,
  `number` INT NULL,
  `begin` DATE NULL,
  `end` DATE NULL,
  PRIMARY KEY (`id_sprint`),
  INDEX `id_project_idx` (`id_project` ASC),
  CONSTRAINT `id_project_sprint`
    FOREIGN KEY (`id_project`)
    REFERENCES `scrumdev`.`project` (`id_project`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `scrumdev`.`task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scrumdev`.`task` (
  `id_task` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  `content` TEXT NULL,
  `cost` INT NULL,
  `status` VARCHAR(20) NULL,
  `id_user` INT NULL,
  `id_sprint` INT NULL,
  PRIMARY KEY (`id_task`),
  INDEX `id_user_idx` (`id_user` ASC),
  INDEX `id_sprint_idx` (`id_sprint` ASC),
  CONSTRAINT `id_user_task`
    FOREIGN KEY (`id_user`)
    REFERENCES `scrumdev`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_sprint_task`
    FOREIGN KEY (`id_sprint`)
    REFERENCES `scrumdev`.`sprint` (`id_sprint`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `scrumdev`.`dependency`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scrumdev`.`dependency` (
  `id_dependancy` INT NOT NULL AUTO_INCREMENT,
  `id_task1` INT NULL,
  `id_task2` INT NULL,
  PRIMARY KEY (`id_dependancy`),
  INDEX `id_task1_idx` (`id_task1` ASC),
  INDEX `id_task2_idx` (`id_task2` ASC),
  CONSTRAINT `id_task1_dependancy`
    FOREIGN KEY (`id_task1`)
    REFERENCES `scrumdev`.`task` (`id_task`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_task2_dependancy`
    FOREIGN KEY (`id_task2`)
    REFERENCES `scrumdev`.`task` (`id_task`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `scrumdev`.`task_us`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scrumdev`.`task_us` (
  `id_task_us` INT NOT NULL AUTO_INCREMENT,
  `id_task` INT NULL,
  `id_us` INT NULL,
  PRIMARY KEY (`id_task_us`),
  INDEX `id_task_idx` (`id_task` ASC),
  INDEX `id_us_idx` (`id_us` ASC),
  CONSTRAINT `id_task_task_us`
    FOREIGN KEY (`id_task`)
    REFERENCES `scrumdev`.`task` (`id_task`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_us_task_us`
    FOREIGN KEY (`id_us`)
    REFERENCES `scrumdev`.`userstory` (`id_us`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
