
<?php echo $this->getContent() ?>

<div align="right">
    <?php echo $this->tag->linkTo(array("user/new", "Inscription")) ?>
</div>

<?php echo $this->tag->form(array("user/login", "autocomplete" => "off")) ?>

<div align="center">
    <h1>Connexion</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="login">Identifiant: </label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("login", "size" => 20)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="password">Mot de passe: </label>
        </td>
        <td align="left">
            <?php echo $this->tag->passwordField(array("password", "size" => 30)) ?>
        </td>
    </tr>

    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Valider") ?></td>
    </tr>
</table>

</form>
