<?php echo $this->getContent() ?>

<table width="100%">
    <tr>
        <td align="right"><?php echo $this->tag->linkTo(array("user/new", "Inscription", "class" => "btn")) ?></td>
    </tr>
</table>

<h1>Connexion</h1>

<?php echo $this->tag->form(array("user/login", "autocomplete" => "off")) ?>
    <table>
        <tr>
            <td align="right">
                <label for="login">Identifiant: </label>
            </td>
            <td align="left">
                <?php echo $this->tag->textField(array("login", "size" => 20)) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="password">Mot de passe: </label>
            </td>
            <td align="left">
                <?php echo $this->tag->passwordField(array("password", "size" => 30)) ?>
            </td>
        </tr>

        <tr>
            <td></td>
            <td><?php echo $this->tag->submitButton(array("Valider", "class" => "btn btn-primary btn-large")) ?></td>
        </tr>
    </table>
</form>
