<?php echo $this->getContent(); ?>

<table width="100%">
    <tr>
        <td align="left"><?php echo $this->tag->linkTo(array("user", "Retour", "class" => "btn")) ?></td>
    </tr>
</table>

<h1>Inscription</h1>

<?php echo $this->tag->form("user/create") ?>
    <table>
        <tr>
            <td align="right">
                <label for="login">Identifiant</label>
            </td>
            <td align="left">
                <?php echo $this->tag->textField(array("login", "size" => 30)) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="email">Email</label>
            </td>
            <td align="left">
                <?php echo $this->tag->emailField(array("email", "size" => 30)) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="password">Mot de passe</label>
            </td>
            <td align="left">
                <?php echo $this->tag->passwordField(array("password", "size" => 30)) ?>
            </td>
        </tr>

        <tr>
            <td></td>
            <td><?php echo $this->tag->submitButton(array("Valider", "class" => "btn btn-primary btn-large")) ?></td>
        </tr>
    </table>
</form>
