
<?php echo $this->tag->form("user/create") ?>

<table width="100%">
    <tr>
        <td align="left"><?php echo $this->tag->linkTo(array("user", "Retour")) ?></td>
    </tr>
</table>

<?php echo $this->getContent(); ?>

<div align="center">
    <h1>Inscription</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="login">Indentifiant</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("login", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="email">Email</label>
        </td>
        <td align="left">
            <?php echo $this->tag->emailField(array("email", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="password">Mot de passe</label>
        </td>
        <td align="left">
            <?php echo $this->tag->passwordField(array("password", "size" => 30)) ?>
        </td>
    </tr>

    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Valider") ?></td>
    </tr>
</table>

</form>
