<?php echo $this->getContent(); ?>

<?php if ($this->session->has('auth')){?>

<table width="100%">
    <tr>
        <td align="right"> <?php echo $this->tag->linkTo(array("project/new", "Nouveau projet", "class" => "btn")) ?></td>
    </tr>
</table>


<table class="browse" align="center">
	<thead>
		<tr>
			<th>Titre projet</th>
			<th>Description</th>
		</tr>
	</thead>
	<tbody>
	<?php foreach ($page->items as $project) { ?>
		<tr>
			<td><?php echo $project->title ?></td>
			<td><?php echo $project->content ?></td>
			<td><?php echo $this->tag->linkTo(array("project/show/" . $project->id_project, "Détails")); ?></td>
			
		</tr>
	<?php } ?>
	</tbody>
	<tbody>
		<tr>
			<td colspan="2" align="right">
				<table align="center">
					<tr>
						<td><?php echo $this->tag->linkTo("project/index", "Début") ?></td>
						<td><?php echo $this->tag->linkTo("project/index?page=" . $page->before, "Précédent") ?></td>
						<td><?php echo $this->tag->linkTo("project/index?page=" . $page->next, "Suivant") ?></td>
						<td><?php echo $this->tag->linkTo("project/index?page=" . $page->last, "Fin") ?></td>
						<td><?php echo $page->current, "/", $page->total_pages ?></td>
					</tr>
				</table>
			</td>
		</tr>
	</tbody>
</table>


<?php } else { 
    $this->flash->error("Vous devez être connecté pour avoir accès à cette page.");
} ?>