<?php echo $this->getContent(); ?>

<table width="100%">
    <tr>
        <td align="left">
            <?php echo $this->tag->linkTo(array("member/myproject", "Mes projets", "class" => "btn")); ?>
        </td>
        <td align="right">
            <?php echo $this->tag->linkTo(array("project/new", "Nouveau projet", "class" => "btn")) ?>
        </td>
    </tr>
</table>

<div><h1>Projets</h1><br/></div>

<table class="table" style="width:80% !important">
	<thead>
		<tr>
			<th>Intitulé</th>
			<th>Description</th>
            <th></th>
		</tr>
	</thead>
	<tbody>
	<?php foreach ($page->items as $project) { ?>
		<tr>
			<td><?php echo $project->title ?></td>
			<td><?php echo $project->content ?></td>
			<td><?php echo $this->tag->linkTo(array("project/show/" . $project->id_project, "Détails")); ?></td>
			
		</tr>
	<?php } ?>
	</tbody>
</table>
<table width="10%">
    <tr>
	   <td><?php echo $this->tag->linkTo("project/index", "First") ?></td>
        <td><?php echo $this->tag->linkTo("project/index?page=" . $page->before, "Previous") ?></td>
	   <td><?php echo $this->tag->linkTo("project/index?page=" . $page->next, "Next") ?></td>
		<td><?php echo $this->tag->linkTo("project/index?page=" . $page->last, "Last") ?></td>
    </tr>
</table>
<?php echo $page->current, "/", $page->total_pages ?>
