
<?php echo $this->getContent() ?>

<div align="right">
    <?php echo $this->tag->linkTo(array("project/new", "Ajouter")) ?>
</div>

<?php echo $this->tag->form(array("user/login", "autocomplete" => "off")) ?>

<div align="center">
    <h1>Projet</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="login">Titre</label>
        </td>
        <td align="left">
            <?php echo $title ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="password">Description </label>
        </td>
        <td align="left">
            <?php echo $content ?>
        </td>
    </tr>

    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Valider") ?></td>
    </tr>
</table>

</form>
