<?php echo $this->getContent(); ?>

<table width="100%">
    <tr>
        <td align="left"><?php echo $this->tag->linkTo(array("project", "Retour", "class"=>"btn")) ?></td>
    </tr>
</table>

<h1>Nouveau Projet</h1>

<?php echo $this->tag->form("project/create") ?>
    <table>
        <tr>
            <td align="right">
                <label for="title">Titre</label>
            </td>
            <td align="left">
                <?php echo $this->tag->textField(array("title", "size" => 30)) ?>
            </td>
        </tr>
      
        <tr>
            <td align="right">
                <label for="access">Description</label>
            </td>
            <td align="left">
                <?php echo $this->tag->textArea(array("content", "cols" => 100, "rows" => 10)) ?>
            </td>
        </tr>

    	  <tr>
            <td align="right">
                <label for="content">Accès public</label>
            </td>
            <td align="left">
                <?php echo $this->tag->checkField(array("access", "value" => 1)) ?>
            </td>
        </tr>
    	
        <tr>
            <td></td>
            <td><?php echo $this->tag->submitButton("Valider") ?></td>
        </tr>
    </table>
</form>
