
<?php echo $this->tag->form("project/create") ?>

<table width="100%">
    <tr>
        <td align="left"><?php echo $this->tag->linkTo(array("project", "Retour")) ?></td>
    </tr>
</table>

<?php echo $this->getContent(); ?>

<div align="center">
    <h1>Nouveau Projet</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="title">Titre</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("title", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="content">Description</label>
        </td>
        <td align="left">
            <?php echo $this->tag->emailField(array("content", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="access">Accés</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textArea(array("content", "cols" => 100, "rows" => 10)) ?>
        </td>
    </tr>

    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Valider") ?></td>
    </tr>
</table>

</form>
