<?php echo $this->getContent(); ?>

<?php if ($this->session->has('auth')){?>

<table width="100%">
    <tr>
        <td align="left"><?php echo $this->tag->linkTo(array("project/index", "Retour", "class"=>"btn")); ?></td>
    </tr>
</table>


<table>
    <tr>
        <td align="right">
            <label for="title">Title</label>
        </td>
        <td align="left">
            <?php echo $project->title ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="content">Content</label>
        </td>
        <td align="left">
            <?php echo $project->content ?>
        </td>
    </tr>

    <tr>
		<td><?php echo $this->tag->linkTo(array("member/inscription".$project->id_project, "Postuler")); ?></td>
        <td><?php echo $this->tag->linkTo(array("backlog/index", "Backlog")); ?></td>
		<td><?php echo $this->tag->linkTo(array("member/index", "Liste Membres")); ?></td>
		<td><?php echo $this->tag->linkTo(array("project/edit/" . $project->id_project, "edition")); ?></td>
    </tr>
</table>

<?php } else { 
    $this->flash->error("Vous devez être connecté pour avoir accès à cette page.");
} ?>