<?php use Phalcon\Tag; ?>

<?php echo $this->getContent(); ?>

<table width="100%">
    <tr>
        <td align="left">
            <?php echo $this->tag->linkTo(array("user/index", "Go Back")); ?>
        </td>
    </tr>
</table>

<div align="right">
    <?php echo $this->tag->linkTo(array("project/index", "back")) ?>
	<table class="browse" align="center">
		<thead>
			<tr>
				<th>Utilisateur</th>
			</tr>
		</thead>
		<tbody>
		<?php foreach ($page->items as $member) { ?>
			<tr>
				<td><?php echo $member->user->login ?></td>
				
				
			</tr>
		<?php } ?>
		</tbody>
		<tbody>
			<tr>
				<td colspan="2" align="right">
					<table align="center">
						<tr>
							<td><?php echo $this->tag->linkTo("project/index", "First") ?></td>
							<td><?php echo $this->tag->linkTo("project/index?page=" . $page->before, "Previous") ?></td>
							<td><?php echo $this->tag->linkTo("project/index?page=" . $page->next, "Next") ?></td>
							<td><?php echo $this->tag->linkTo("project/index?page=" . $page->last, "Last") ?></td>
							<td><?php echo $page->current, "/", $page->total_pages ?></td>
						</tr>
					</table>
				</td>
			</tr>
		</tbody>
	</table>
</div>
