<?php echo $this->getContent(); ?>

<table width="100%">
    <tr>
        <td align="left">
            <?php echo $this->tag->linkTo(array("project/index", "Retour", "class" => "btn")); ?>
        </td>
    </tr>
</table>

<header><h1>Mes projets</h1></header>

<table class="table" style="width:80% !important">
    <thead>
        <tr>
            <th>Intitulé</th>
            <th>Status</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($page->items as $member) { ?>
			<tr>
				<td><?php echo $member->project->title ?></td>
				<td><?php 
				switch($member->status){
					case 0:
						echo "ScrumMaster";
						break;
					case 1:
						echo "Membre";
						break;
					case 2:
						echo "Invitation";
						break;
					case 3 :
						echo "En attente";
						break;
						}
				?></td>
				<td><?php echo $this->tag->linkTo(array("project/show/" . $member->id_project, "Détails")); ?></td>				
				<td><?php 
				switch($member->status){
					
					case 1:
						echo $this->tag->linkTo(array("member/fire/".$member->id_member, "Quitter"));
						break;
					case 2:
						echo $this->tag->linkTo(array("member/accept/".$member->id_member, "Accepter"));
						echo $this->tag->linkTo(array("member/fire/".$member->id_member, "Refuser"));
						break;
					case 3 :
						echo $this->tag->linkTo(array("member/fire/".$member->id_member, "Quitter"));
						break;
						}					
						
					  ?> </td>
			</tr>
		<?php } ?>
    </tbody>
</table>
<table width="10%">
    <tr>
	   <td><?php echo $this->tag->linkTo("member/myproject", "First") ?></td>
        <td><?php echo $this->tag->linkTo("member/myproject?page=" . $page->before, "Previous") ?></td>
	   <td><?php echo $this->tag->linkTo("member/myproject?page=" . $page->next, "Next") ?></td>
		<td><?php echo $this->tag->linkTo("member/myproject?page=" . $page->last, "Last") ?></td>
    </tr>
</table>
<?php echo $page->current, "/", $page->total_pages ?>
