<?php echo $this->getContent(); ?>

<?php echo $this->tag->form("task/newdependancy") ?>

<table width="100%">
    <tr>
        <td align="left"><?php echo $this->tag->linkTo(array("task", "Back")) ?></td>
        <td align="right"><?php echo $this->tag->submitButton("Save") ?></td>
    </tr>
</table>

<div align="center">
    <h1>Dependances de la tache</h1>
</div>

<table class="browse" align="center">
		<thead>
			<tr>
				<th>Titre tache</th>
				<th>Description</th>
				<th>Cout</th>
				<th>Etat</th>
			</tr>
		</thead>
		<tbody>
		<?php foreach ($page as $task) { ?>
			<tr>
				<td><?php echo $task->title ?></td>
				<td><?php echo $task->content ?></td>
				<td><?php echo $task->cost ?></td>
				<td><?php if($task->dep)
							echo $this->tag->checkField(array("dependancy[]", "value" => $task->id_task, "checked" => "checked"));
						else
							echo $this->tag->checkField(array("dependancy[]", "value" => $task->id_task));?></td>
			</tr>
			<tr>
				<td><?php echo $this->tag->hiddenField("id_task") ?></td>
			</tr>
		<?php } ?>
		</tbody>
	</table>