<?php use Phalcon\Tag; ?>

<?php echo $this->getContent(); ?>

<table width="100%">
    <tr>
        <td align="left">
            <?php echo $this->tag->linkTo(array("sprint/show/" . $this->session->get("id_sprint"), "Retour", "class"=>"btn")) ?>
        </td>
		<td align="right">
			<?php echo $this->tag->linkTo(array("task/new", "Nouvelle Tâche", "class"=>"btn")) ?>
		</td>
    </tr>
</table>

<div align="right">
	<table align="center" class="table" style="width:80% !important">
		<thead>
			<tr>
				<th>Titre</th>
				<th>Description</th>
				<th>Cout</th>
				<th>Dépendances</th>
				<th>User Stories</th>
				<th>Etat</th>
			</tr>
		</thead>
		<tbody>
		<?php foreach ($page as $task) { ?>
			<tr>
				<td><?php echo $task->title ?></td>
				<td><?php echo $task->content ?></td>
				<td><?php echo $task->cost ?></td>
				<td><?php echo $this->tag->linkTo(array("task/dependancy/" . $task->id_task, "Dépendances de T" . $task->id_task)); ?></td>
				<td><?php echo $this->tag->linkTo(array("task/taskus/" . $task->id_task, "US de T" . $task->id_task)); ?></td>
				<td><?php echo $task->status;?></td>
				<td><?php echo $this->tag->linkTo(array("task/edit/" . $task->id_task, "Edit")); ?></td>
				<td><?php echo $this->tag->linkTo(array("task/delete/" . $task->id_task, "Delete")); ?></td>
			</tr>
		<?php } ?>
		</tbody>
	</table>
</div>
