<?php use Phalcon\Tag; ?>

<?php echo $this->getContent(); ?>

<table width="100%">
    <tr>
        <td align="left">
            <?php echo $this->tag->linkTo(array("sprint/index", "Go Back")); ?>
        </td>
    </tr>
</table>

<div align="right">
    <?php echo $this->tag->linkTo(array("task/new", "New Task")) ?>
	<table class="browse" align="center">
		<thead>
			<tr>
				<th>Titre</th>
				<th>Description</th>
				<th>Cout</th>
				<th>Etat</th>
				<!--<th>Membre</th>-->
			</tr>
		</thead>
		<tbody>
		<?php foreach ($page as $task) { ?>
			<tr>
				<td><?php echo $task->title ?></td>
				<td><?php echo $task->content ?></td>
				<td><?php echo $task->cost ?></td>
				<td><?php echo $this->tag->linkTo(array("task/dependancy/" . $task->id_task, "Dependances")); ?></td>
				<td><?php echo $this->tag->linkTo(array("task/edit/" . $task->id_task, "Edit")); ?></td>
				<td><?php echo $this->tag->linkTo(array("task/delete/" . $task->id_task, "Delete")); ?></td>
			</tr>
		<?php } ?>
		</tbody>
	</table>
</div>
