
<?php echo $this->tag->form("task/create") ?>

<table width="100%">
    <tr>
        <td align="left"><?php echo $this->tag->linkTo(array("task", "Retour")) ?></td>
    </tr>
</table>

<?php echo $this->getContent(); ?>

<div align="center">
    <h1>Inscription</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="title">Titre</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("title", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="content">Description</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("content", "size" => 254)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="cost">Cout</label>
        </td>
        <td align="left">
            <?php echo $this->tag->numericField(array("cost", "value">0)) ?>
        </td>
    </tr>
	
    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Valider") ?></td>
    </tr>
</table>

</form>
